### ISSUE TITLE
Configuring regions

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#6]
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Configuring-Regions

Possible to add some administrative layers in the Atlas? So they appear in the regions Menu?

Uploading spatial layers to the Spatial portal seems to work fine. Are the regions in the regions module connected with the layers in the spatial portal?

**Comment by stenmigerode** [comment]
There is still something I am probably overlooking for the Gemeentegrenzen. I am seeing the ID on the regions portal, instead of the name.
![afbeelding](https://user-images.githubusercontent.com/27133403/196701864-df022875-bba4-480d-9b01-e6c08878e840.png)


Clicking on the city, the map is zooming to a bizarre location. I need to check if somehow the Lambert coordinates were imported instead of CRS or WGS84

**Comment by stenmigerode** [comment]
Carine will convert the shapefile to WGS84. It contained only information for the Lambert72 CRS

**Comment by DimEvil** [comment]
I have other layers... I could also convert them. We don't need them all,
just enough to showcase.

Op wo 19 okt. 2022 16:39 schreef Sten Migerode ***@***.***>:

**Comment by stenmigerode** [comment]
Gemeentegrenzen have been added to the regions menu.
