### ISSUE TITLE
create area spatial portal, bounding box not visible

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#81]
When creating an area in the spatial portal;

Add to map ->  Area --> Draw Bounding box

![image](https://github.com/user-attachments/assets/65f4f1d4-70e9-4e95-95a3-13b224a73a65)

**no bounding box is seen**, although the box is there: Tools --> Area report -> map all species  (gives occurrences for all the species in the box and makes it visible :) )

![image](https://github.com/user-attachments/assets/5f39d5ee-26ee-4fe5-9c51-d73e1b23a046)

**Comment by StefanVanDyck** [comment]
Problem was the initGeoserver task did not run correctly.
Possibly because the DB field for task history did not allow big strings to be saved.
Or alternatively because the postgis layer in geoserver had an incorrect host.

Fix was to change the DB field type, set the postgis host manually in Geoserver and execute initGeoserver again
